### ISSUE TITLE
storeMessage cannot deal with dynamic binding properly

### ISSUE THREAD

**Issue by tovleeuw** [waylayio/Sensors#50]
How to replicate:

if you give a payload like this
{"NO_DATA":1,"timestamp": 2022-02-28T16:40:23.981Z}
then it fails
![image](https://user-images.githubusercontent.com/38496857/156025044-1ae1f752-aedf-4fa1-98d6-eb0ce5d880c4.png)

if you give a payload like this
{"NO_DATA":1,"timestamp": "2022-02-28T16:40:23.981Z"}
then it succeeds

which basically means that you have to do this
{"NO_DATA":1,"timestamp": $${nodes.yoursensor.rawdata.timestamp}}
and you cannot do this
{"NO_DATA":1,"timestamp": ${nodes.yoursensor.rawdata.timestamp}}

which makes no sense for the rule designer

**Comment by francisdb** [comment]
also related to https://github.com/waylayio/WaylayEngine/issues/1956

`${}` was originally for templating emails, where json quoting and co is not what you want. eg "Hello ${user.name}"
therefore we added `$${}` for the json building use case
then we also added some magic to transform things automatically to json if it looks like json

We understand this might be confusing but but these were decisions taken a long time ago. We can't just change defaults.
Using `$${}` everywhere should help for now.

This can't be fixed by the plugin, will add this specific case to the above issue.
